/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '18-6-27 下午8:29' with Gradle 3.2.1
 *
 * @author Administrator, @date 18-6-27 下午8:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
